### ISSUE TITLE
Instant crash when trying to run the mod.

### ISSUE THREAD

**Issue by varappdev** [MCrafterzz/VanillaAutomated#1]
Hello. I have issues while trying to start my fabric instance with this mod on. Can you please tell me what is the issue? 
[crash-2020-07-03_13.17.34-client.txt](https://github.com/MCrafterzz/VanillaAutomated/files/4869630/crash-2020-07-03_13.17.34-client.txt)

**Comment by MarcusElg** [comment]
> Hello. I have issues while trying to start my fabric instance with this mod on. Can you please tell me what is the issue?
> [crash-2020-07-03_13.17.34-client.txt](https://github.com/MCrafterzz/VanillaAutomated/files/4869630/crash-2020-07-03_13.17.34-client.txt)

Yes you don't have libgui installed

**Comment by MarcusElg** [comment]
Also it's inportant that you have the 2.0.1 version of libgui

**Comment by varappdev** [comment]
I cannot find the 2.0.1 version anywhere, I can only find 1.8.0

**Comment by varappdev** [comment]
Nevermind, I went to their github page and found it, please tell me if I can install newer versions
