### ISSUE TITLE
Mob net - Can't pickup villagers, and issues with placement location of other mobs

### ISSUE THREAD

**Issue by shikyo13** [MCrafterzz/VanillaAutomated#5]
Fabric Server Version: 0.6.1.45 , vanillautomated-1.0.4 .

1. When trying to pickup villagers you just open the GUI instead. 

Expected behavior: Pick up the villager

2. When trying to place a mob against (not on top) a block it is placed on random adjacent block or inside a wall and suffocates. 
Example: trying to place a cow in a 1x1 hole on top of a hopper results in the cow suffocating inside the walls instead. 

Expected behavior: mob is placed centered on the targeted block, or centered in the air if placed against a vertical face to drop down.

**Comment by MarcusElg** [comment]
> Fabric Server Version: 0.6.1.45 , vanillautomated-1.0.4 .
> 
> When trying to pickup villagers you just open the GUI instead.
> 
> Expected behavior: Pick up the villager
> 
> When trying to place a mob against (not on top) a block it is placed on random adjacent block or inside a wall and suffocates.
> Example: trying to place a cow in a 1x1 hole on top of a hopper results in the cow suffocating inside the walls instead.
> 
> Expected behavior: mob is placed centered on the targeted block, or centered in the air if placed against a vertical face to drop down.

Thanks for reporting these! Both of them are fixed in the upcoming update that will come sometime today :D

**Comment by MarcusElg** [comment]
Fixed in 1.1.0
