### ISSUE TITLE
Feature request: detector+breaker (observer+piston alternative)

### ISSUE THREAD

**Issue by ghost** [MCrafterzz/VanillaAutomated#7]
The observer and piston combo is a very popular and lag friendly solution for automated farms.
I'd love to see these two blocks combined in a single block:
  - It is activated on a changing blockstate
  - It acts as a piston extending, breaking the updated block
  - This would only work for blocks that would pop off when pushed (crops, bamboo, kelp, sugar cane, ...)
  - This block wouldn't emit a redstone signal
  - Optionally, this detector/breaker could work in all 4 cardinal directions, allowing for small vanilla-style farms.

This entire suggestion is based on the assumption that the block breaker is a ticking block, checking regularly for something to break.  If the block breaker is only triggered on the statechange of the neighbouring block, then this tick/lag friendly solution already exists.

The crafting recipe for this block would include either the detector and piston(s), or need the materials (quartz, redstone, iron) required to craft those.

**Comment by MarcusElg** [comment]
Interesting idea but what would it be used for? The farmer can already be used for crops, kelp etc. Combine that with the mob farm block with a skeleton in it and hook it up to a crafter or crusher to convert it to bonemeal and then it's unbeatable.

**Comment by ghost** [comment]
You're right, in the context of your mod it does make little sense.  Here's my way of thinking:

While I love the concept and machines, they feel OP compared to the collection of mods added to my server.  Because of that, I have nerfed the speed of the farmer and mob farm block, so they can't be used to create a net positive power system.  By default, a single blaze rod can create 3 others.  This nerf makes vanilla-style farms a better choice for certain use-cases.
