### ISSUE TITLE
Display glitch in crafter GUI when using several crafters

### ISSUE THREAD

**Issue by Adirelle** [MCrafterzz/VanillaAutomated#9]
When using several crafters, the crafting grid is messed up: in a given crafter, you can see items inserted into other crafters, and vice versa. This is just a visual glitch though, as they all work as intended.

Version 1.1.3 on minecraft 1.16.2.

**Comment by Adirelle** [comment]
Example with Resourceful Tools' bamboo sheet recipes.
I have two crafters: the first one crafts a bamboo sheet from 9 bamboo sticks, the second one craft a large bamboo sheet from 9 bamboo sheets. Here is what I can see when I look at the second one while the whole pipeline is running:

![2020-08-31_19 17 47](https://user-images.githubusercontent.com/24633/91747558-b323c180-ebbe-11ea-983c-8e9475ab6b68.png)

**Comment by MarcusElg** [comment]
If you close and open the crafter again does it still look incorrect?

**Comment by Adirelle** [comment]
Yep. It only bugs on inventory updates.

**Comment by MarcusElg** [comment]
I can replicate it

**Comment by Adirelle** [comment]
Sorry, I meant it looks correct on open/close but starts messing up when items are inserted by hoppers.

The crafters re set up like this (side view) :

| V = Hopper, C = Crafter |
| - |
| V |
| C |
| V |
| C |  

Whenever an item gets inserted in any of them by the hoppers, it shows on the GUI of the crafter I am looking at, even if the item is actually inserted in the *other* crafter.

**Comment by MarcusElg** [comment]
https://www.curseforge.com/minecraft/mc-mods/vanilla-automated/files/3048857 Fixed in 1.1.4 :D Thanks for reporting!
